
package com.glarimy.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bank", targetNamespace = "http://jaxws.glarimy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Bank {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountOwner", targetNamespace = "http://jaxws.glarimy.com/", className = "com.glarimy.jaxws.GetAccountOwner")
    @ResponseWrapper(localName = "getAccountOwnerResponse", targetNamespace = "http://jaxws.glarimy.com/", className = "com.glarimy.jaxws.GetAccountOwnerResponse")
    @Action(input = "http://jaxws.glarimy.com/Bank/getAccountOwnerRequest", output = "http://jaxws.glarimy.com/Bank/getAccountOwnerResponse")
    public String getAccountOwner(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openAccount", targetNamespace = "http://jaxws.glarimy.com/", className = "com.glarimy.jaxws.OpenAccount")
    @ResponseWrapper(localName = "openAccountResponse", targetNamespace = "http://jaxws.glarimy.com/", className = "com.glarimy.jaxws.OpenAccountResponse")
    @Action(input = "http://jaxws.glarimy.com/Bank/openAccountRequest", output = "http://jaxws.glarimy.com/Bank/openAccountResponse")
    public int openAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
